import Head from 'next/head'
import Layout from '../components/Layout'
import Nav from '../components/Nav'
import Intro from '../components/Intro/Intro'
import About from '../components/About/About'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Nav />
        <Intro />
        <About />
      </Layout>
    </>
  )
}
